spring:
  datasource:
      url: jdbc:mysql://39.105.186.116:3306/cboard?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 'jdk8!Wkhello:'
      name: CBoard Meta Data
      validationQuery: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver